//! Code generation: LLVM IR module -> UVM assembly text.
//!
//! Strategy (correctness-first, see plan.md):
//! - Each instruction result gets a local slot; parameters are read via
//!   `get_arg`. Lowering an instruction = push operands, emit the typed op,
//!   `set_local` the result. The operand stack is empty between instructions.
//! - Integer values are kept zero-extended to their width in a 64-bit slot.
//!   Use natural-width ops (`_u32`/`_i32` for width <= 32, `_u64`/`_i64` for
//!   64). After a sub-32-bit op, truncate to re-establish the invariant; for
//!   signed sub-32-bit ops, sign-extend operands first.

use rustc_hash::FxHashMap as HashMap;

use crate::ast::*;
use crate::layout::Layout;

pub struct Codegen<'a>
{
    module: &'a Module,
    #[allow(dead_code)]
    layout: Layout<'a>,
    out: String,
    /// Counter for generating unique labels (branch edges, select, switch).
    label_counter: usize,
}

/// Per-function lowering context.
struct FnCtx<'f>
{
    name: String,
    /// Parameter name -> argument index.
    params: HashMap<&'f str, usize>,
    /// Instruction-result name -> local slot index.
    slots: HashMap<&'f str, usize>,
    /// Block label -> basic block (for resolving phi edges).
    blocks: HashMap<&'f str, &'f BasicBlock>,
}

impl<'a> Codegen<'a>
{
    pub fn new(module: &'a Module) -> Self
    {
        Codegen { module, layout: Layout::new(module), out: String::new(), label_counter: 0 }
    }

    pub fn generate(mut self) -> Result<String, String>
    {
        self.line("#");
        self.line("# Generated by the llbc compiler (LLVM IR -> UVM).");
        self.line("#");
        self.line("");
        self.gen_data();
        self.gen_code()?;
        Ok(self.out)
    }

    fn gen_data(&mut self)
    {
        // Globals are emitted here in a later phase; empty for now.
        self.line(".data;");
        self.line("");
    }

    fn gen_code(&mut self) -> Result<(), String>
    {
        self.line(".code;");
        self.line("# program entry: run main, then halt with its return value");
        self.line("call main, 0;");
        self.line("ret;");
        self.line("");

        // Copy out the module reference so the loop doesn't borrow `self`.
        let module = self.module;
        for f in &module.functions {
            if !f.is_decl() {
                self.gen_function(f)?;
            }
        }
        Ok(())
    }

    fn gen_function(&mut self, f: &'a Function) -> Result<(), String>
    {
        // Build the lowering context: parameter and result-slot maps.
        let mut params = HashMap::default();
        for (i, p) in f.params.iter().enumerate() {
            if let Some(name) = &p.name {
                params.insert(name.as_str(), i);
            }
        }
        let mut slots = HashMap::default();
        let mut num_slots = 0usize;
        let mut blocks = HashMap::default();
        for bb in &f.blocks {
            blocks.insert(bb.label.as_str(), bb);
            for inst in &bb.insts {
                if let Some(dest) = &inst.dest {
                    slots.insert(dest.as_str(), num_slots);
                    num_slots += 1;
                }
            }
        }
        let ctx = FnCtx { name: sanitize(&f.name), params, slots, blocks };

        self.line(&format!("# {} @{}({} params)", type_str(&f.ret_ty), f.name, f.params.len()));
        self.line(&format!("{}:", ctx.name));

        // Reserve local slots (push_0n now takes a u16 operand).
        if num_slots > 0 {
            if num_slots > u16::MAX as usize {
                return Err(format!("function {} needs {} locals (> 65535)", f.name, num_slots));
            }
            self.line(&format!("push_0n {};", num_slots));
        }

        for bb in &f.blocks {
            self.line(&format!("{}:", block_label(&ctx.name, &bb.label)));
            for inst in &bb.insts {
                self.gen_inst(&ctx, inst)?;
            }
            self.gen_term(&ctx, &bb.label, &bb.term)?;
        }

        self.line("");
        Ok(())
    }

    // -- instructions ---------------------------------------------------------

    fn gen_inst(&mut self, ctx: &FnCtx, inst: &Inst) -> Result<(), String>
    {
        match &inst.kind {
            InstKind::Bin { op, ty, lhs, rhs } => {
                self.gen_bin(ctx, *op, ty, lhs, rhs)?;
                self.store_dest(ctx, inst.dest.as_deref())?;
            }
            InstKind::Conv { op, from_ty, val, to_ty } => {
                self.gen_conv(ctx, *op, from_ty, val, to_ty)?;
                self.store_dest(ctx, inst.dest.as_deref())?;
            }
            InstKind::ICmp { pred, ty, lhs, rhs } => {
                self.gen_icmp(ctx, *pred, ty, lhs, rhs)?;
                self.store_dest(ctx, inst.dest.as_deref())?;
            }
            InstKind::Select { cond, ty, tval, fval } => {
                self.gen_select(ctx, cond, ty, tval, fval)?;
                self.store_dest(ctx, inst.dest.as_deref())?;
            }
            // Phi results are written on the predecessor edges, so the phi
            // instruction itself emits no code.
            InstKind::Phi { .. } => {}
            other => return Err(format!("codegen: instruction not yet implemented: {}", kind_name(other))),
        }
        Ok(())
    }

    fn gen_bin(&mut self, ctx: &FnCtx, op: BinOp, ty: &Type, lhs: &Value, rhs: &Value) -> Result<(), String>
    {
        let w = int_width(ty)?;
        let ow = if w <= 32 { 32 } else { 64 };
        let signed = matches!(op, BinOp::SDiv | BinOp::SRem | BinOp::AShr);

        // lhs is always a value operand.
        self.push_value(ctx, lhs, w)?;
        if signed && w < ow {
            self.emit_sext(w, ow)?;
        }
        // rhs: a value for div/rem (sign-extend if signed); a shift count for shifts.
        self.push_value(ctx, rhs, w)?;
        if matches!(op, BinOp::SDiv | BinOp::SRem) && w < ow {
            self.emit_sext(w, ow)?;
        }

        self.line(&format!("{};", bin_mnemonic(op, ow)));

        // Re-establish the width invariant for sub-32-bit results.
        if w < 32 {
            self.emit_trunc_to(w);
        }
        Ok(())
    }

    fn gen_conv(&mut self, ctx: &FnCtx, op: ConvOp, from_ty: &Type, val: &Value, to_ty: &Type) -> Result<(), String>
    {
        let fw = int_width(from_ty)?;
        let tw = int_width(to_ty)?;
        self.push_value(ctx, val, fw)?;
        match op {
            // trunc to a narrower width.
            ConvOp::Trunc => self.emit_trunc_to(tw),
            // The value is already zero-extended in its slot, so zext is free.
            ConvOp::ZExt => {}
            ConvOp::SExt => self.emit_sext(fw, tw)?,
            // Pointers are 64-bit ints; only width adjustment is needed.
            ConvOp::PtrToInt => {
                if tw < 64 {
                    self.emit_trunc_to(tw);
                }
            }
            ConvOp::IntToPtr => {} // zero-extend to 64-bit = no-op
            ConvOp::BitCast => {}  // same bits
        }
        Ok(())
    }

    fn gen_icmp(&mut self, ctx: &FnCtx, pred: ICmpPred, ty: &Type, lhs: &Value, rhs: &Value) -> Result<(), String>
    {
        let w = int_width(ty)?;
        let ow = if w <= 32 { 32 } else { 64 };
        let signed = matches!(pred, ICmpPred::Sgt | ICmpPred::Sge | ICmpPred::Slt | ICmpPred::Sle);

        self.push_value(ctx, lhs, w)?;
        if signed && w < ow {
            self.emit_sext(w, ow)?;
        }
        self.push_value(ctx, rhs, w)?;
        if signed && w < ow {
            self.emit_sext(w, ow)?;
        }
        self.line(&format!("{};", icmp_mnemonic(pred, ow)));
        // Result is an i1 (0/1), already satisfying the width invariant.
        Ok(())
    }

    fn gen_select(&mut self, ctx: &FnCtx, cond: &Value, ty: &Type, tval: &Value, fval: &Value) -> Result<(), String>
    {
        let w = int_width(ty)?;
        let l_false = self.fresh_label("sel_false");
        let l_done = self.fresh_label("sel_done");

        self.push_value(ctx, cond, 1)?;
        self.line(&format!("jz {};", l_false));
        self.push_value(ctx, tval, w)?;
        self.line(&format!("jmp {};", l_done));
        self.line(&format!("{}:", l_false));
        self.push_value(ctx, fval, w)?;
        self.line(&format!("{}:", l_done));
        // The selected value is left on the stack for store_dest.
        Ok(())
    }

    // -- terminators ----------------------------------------------------------

    fn gen_term(&mut self, ctx: &FnCtx, pred: &str, term: &Terminator) -> Result<(), String>
    {
        match term {
            Terminator::Ret { val } => match val {
                None => {
                    // `ret void`: UVM `ret` always returns a value, push 0.
                    self.line("push 0;");
                    self.line("ret;");
                }
                Some(tv) => {
                    let w = int_width(&tv.ty)?;
                    self.push_value(ctx, &tv.val, w)?;
                    self.line("ret;");
                }
            },

            Terminator::Br { cond: None, if_true, .. } => {
                self.emit_edge_copies(ctx, pred, if_true)?;
                self.line(&format!("jmp {};", block_label(&ctx.name, if_true)));
            }

            Terminator::Br { cond: Some(c), if_true, if_false } => {
                let if_false = if_false.as_deref().ok_or("conditional br missing false target")?;
                // Each branch edge gets its own phi-copy sequence, which makes
                // critical edges correct without an explicit splitting pass.
                self.push_value(ctx, c, 1)?;
                let l_false = self.fresh_label("br_false");
                self.line(&format!("jz {};", l_false));
                self.emit_edge_copies(ctx, pred, if_true)?;
                self.line(&format!("jmp {};", block_label(&ctx.name, if_true)));
                self.line(&format!("{}:", l_false));
                self.emit_edge_copies(ctx, pred, if_false)?;
                self.line(&format!("jmp {};", block_label(&ctx.name, if_false)));
            }

            Terminator::Switch { ty, val, default, cases } => {
                let w = int_width(ty)?;
                let ow = if w <= 32 { 32 } else { 64 };
                let mut case_targets = Vec::with_capacity(cases.len());
                for (cv, target) in cases {
                    let l_case = self.fresh_label("sw_case");
                    self.push_value(ctx, val, w)?;
                    self.push_int(*cv, w);
                    self.line(&format!("eq_u{};", ow));
                    self.line(&format!("jnz {};", l_case));
                    case_targets.push((l_case, target));
                }
                // Fall through to the default edge.
                self.emit_edge_copies(ctx, pred, default)?;
                self.line(&format!("jmp {};", block_label(&ctx.name, default)));
                // Then the per-case edges.
                for (l_case, target) in case_targets {
                    self.line(&format!("{}:", l_case));
                    self.emit_edge_copies(ctx, pred, target)?;
                    self.line(&format!("jmp {};", block_label(&ctx.name, target)));
                }
            }

            Terminator::Unreachable => self.line("panic;"),
        }
        Ok(())
    }

    /// Emit the phi assignments for the edge `pred -> succ_label`, as a parallel
    /// copy (push all incoming values, then store them into the phi slots in
    /// reverse, so all reads happen before any writes).
    fn emit_edge_copies(&mut self, ctx: &FnCtx, pred: &str, succ_label: &str) -> Result<(), String>
    {
        let succ = match ctx.blocks.get(succ_label) {
            Some(b) => *b,
            None => return Err(format!("branch to unknown block %{}", succ_label)),
        };

        let mut copies: Vec<(usize, &Value, &Type)> = vec![];
        for inst in &succ.insts {
            match &inst.kind {
                InstKind::Phi { ty, incoming } => {
                    let dest = inst.dest.as_deref().ok_or("phi without result name")?;
                    let slot = *ctx
                        .slots
                        .get(dest)
                        .ok_or_else(|| format!("no slot for phi %{}", dest))?;
                    let val = incoming
                        .iter()
                        .find(|(_, p)| p == pred)
                        .map(|(v, _)| v)
                        .ok_or_else(|| format!("phi %{} has no incoming value for predecessor %{}", dest, pred))?;
                    copies.push((slot, val, ty));
                }
                // Phis are only at the start of a block.
                _ => break,
            }
        }

        for (_, val, ty) in &copies {
            let w = int_width(ty)?;
            self.push_value(ctx, val, w)?;
        }
        for (slot, _, _) in copies.iter().rev() {
            self.line(&format!("set_local {};", slot));
        }
        Ok(())
    }

    fn fresh_label(&mut self, hint: &str) -> String
    {
        let n = self.label_counter;
        self.label_counter += 1;
        format!("__{}_{}", hint, n)
    }

    // -- operands -------------------------------------------------------------

    /// Push a value operand (of the given bit width) onto the stack.
    fn push_value(&mut self, ctx: &FnCtx, val: &Value, width: u32) -> Result<(), String>
    {
        match val {
            Value::Local(name) => {
                if let Some(&idx) = ctx.params.get(name.as_str()) {
                    self.line(&format!("get_arg {};", idx));
                } else if let Some(&slot) = ctx.slots.get(name.as_str()) {
                    self.line(&format!("get_local {};", slot));
                } else {
                    return Err(format!("undefined value %{} in {}", name, ctx.name));
                }
            }
            Value::Int(v) => self.push_int(*v, width),
            Value::Null => self.line("push 0;"),
            Value::Undef | Value::Poison | Value::ZeroInit => self.line("push 0;"),
            other => return Err(format!("codegen: operand not yet implemented: {:?}", other)),
        }
        Ok(())
    }

    /// Push an integer constant as its zero-extended `width`-bit pattern, so the
    /// slot satisfies the representation invariant.
    fn push_int(&mut self, v: i128, width: u32)
    {
        let bits: u64 = if width >= 64 {
            v as u128 as u64
        } else {
            ((v as u128) & ((1u128 << width) - 1)) as u64
        };
        self.line(&format!("push {};", bits));
    }

    fn store_dest(&mut self, ctx: &FnCtx, dest: Option<&str>) -> Result<(), String>
    {
        match dest {
            Some(name) => {
                let slot = *ctx.slots.get(name).ok_or_else(|| format!("no slot for %{}", name))?;
                self.line(&format!("set_local {};", slot));
                Ok(())
            }
            None => Err("value-producing instruction has no result name".to_string()),
        }
    }

    // -- width adjustment -----------------------------------------------------

    /// Sign-extend the top-of-stack value from `from` bits to `to` bits.
    fn emit_sext(&mut self, from: u32, to: u32) -> Result<(), String>
    {
        // Direct ops: sx_i{8,16,32}_i{32,64}. For an intermediate width we
        // sign-extend to 32 or 64 and then truncate.
        let mid = if to <= 32 { 32 } else { 64 };
        if (from == 8 || from == 16 || from == 32) && from < mid {
            self.line(&format!("sx_i{}_i{};", from, mid));
            if to < mid {
                self.emit_trunc_to(to);
            }
            Ok(())
        } else {
            Err(format!("unsupported sign extension i{} -> i{}", from, to))
        }
    }

    /// Truncate the top-of-stack value to `w` bits (clearing the upper bits).
    fn emit_trunc_to(&mut self, w: u32)
    {
        match w {
            1 => {
                self.line("push 1;");
                self.line("and_u32;");
            }
            8 => self.line("trunc_u8;"),
            16 => self.line("trunc_u16;"),
            32 => self.line("trunc_u32;"),
            _ => {} // 64: nothing to do
        }
    }

    // -- output ---------------------------------------------------------------

    fn line(&mut self, s: &str)
    {
        self.out.push_str(s);
        self.out.push('\n');
    }
}

// ===========================================================================
// Helpers
// ===========================================================================

/// Integer/pointer bit width (pointers are 64-bit).
fn int_width(ty: &Type) -> Result<u32, String>
{
    match ty {
        Type::Int(w) => Ok(*w),
        Type::Ptr => Ok(64),
        _ => Err(format!("expected an integer/pointer type, got {}", type_str(ty))),
    }
}

fn bin_mnemonic(op: BinOp, w: u32) -> &'static str
{
    use BinOp::*;
    match (op, w) {
        (Add, 32) => "add_u32", (Add, 64) => "add_u64",
        (Sub, 32) => "sub_u32", (Sub, 64) => "sub_u64",
        (Mul, 32) => "mul_u32", (Mul, 64) => "mul_u64",
        (And, 32) => "and_u32", (And, 64) => "and_u64",
        (Or, 32) => "or_u32", (Or, 64) => "or_u64",
        (Xor, 32) => "xor_u32", (Xor, 64) => "xor_u64",
        (Shl, 32) => "lshift_u32", (Shl, 64) => "lshift_u64",
        (LShr, 32) => "rshift_u32", (LShr, 64) => "rshift_u64",
        (AShr, 32) => "rshift_i32", (AShr, 64) => "rshift_i64",
        (UDiv, 32) => "div_u32", (UDiv, 64) => "div_u64",
        (SDiv, 32) => "div_i32", (SDiv, 64) => "div_i64",
        (URem, 32) => "mod_u32", (URem, 64) => "mod_u64",
        (SRem, 32) => "mod_i32", (SRem, 64) => "mod_i64",
        _ => unreachable!("op width must be 32 or 64"),
    }
}

fn icmp_mnemonic(pred: ICmpPred, w: u32) -> String
{
    use ICmpPred::*;
    // eq/ne are sign-agnostic (only `_u` forms exist); the ordering compares
    // pick `_i` (signed) or `_u` (unsigned).
    match pred {
        Eq => format!("eq_u{}", w),
        Ne => format!("ne_u{}", w),
        Ugt => format!("gt_u{}", w),
        Uge => format!("ge_u{}", w),
        Ult => format!("lt_u{}", w),
        Ule => format!("le_u{}", w),
        Sgt => format!("gt_i{}", w),
        Sge => format!("ge_i{}", w),
        Slt => format!("lt_i{}", w),
        Sle => format!("le_i{}", w),
    }
}

/// Sanitize an LLVM name into a valid UVM label (alphanumerics and `_`).
fn sanitize(name: &str) -> String
{
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

fn block_label(fn_name: &str, block: &str) -> String
{
    format!("{}__{}", fn_name, sanitize(block))
}

fn type_str(ty: &Type) -> String
{
    match ty {
        Type::Void => "void".to_string(),
        Type::Int(w) => format!("i{}", w),
        Type::Ptr => "ptr".to_string(),
        Type::Array { len, elem } => format!("[{} x {}]", len, type_str(elem)),
        Type::Struct(_) => "struct".to_string(),
        Type::NamedStruct(n) => format!("%{}", n),
        Type::Func(_) => "fn".to_string(),
        Type::Label => "label".to_string(),
        Type::Metadata => "metadata".to_string(),
    }
}

fn kind_name(k: &InstKind) -> &'static str
{
    match k {
        InstKind::Bin { .. } => "bin",
        InstKind::Conv { .. } => "conv",
        InstKind::ICmp { .. } => "icmp",
        InstKind::Select { .. } => "select",
        InstKind::Load { .. } => "load",
        InstKind::Store { .. } => "store",
        InstKind::Alloca { .. } => "alloca",
        InstKind::GetElementPtr { .. } => "getelementptr",
        InstKind::Phi { .. } => "phi",
        InstKind::Call { .. } => "call",
        InstKind::Freeze { .. } => "freeze",
    }
}

fn term_name(t: &Terminator) -> &'static str
{
    match t {
        Terminator::Ret { .. } => "ret",
        Terminator::Br { .. } => "br",
        Terminator::Switch { .. } => "switch",
        Terminator::Unreachable => "unreachable",
    }
}
