//! Code generation: LLVM IR module -> UVM assembly text.
//!
//! Strategy (correctness-first, see plan.md):
//! - Each instruction result gets a local slot; parameters are read via
//!   `get_arg`. Lowering an instruction = push operands, emit the typed op,
//!   `set_local` the result. The operand stack is empty between instructions.
//! - Integer values are kept zero-extended to their width in a 64-bit slot.
//!   Use natural-width ops (`_u32`/`_i32` for width <= 32, `_u64`/`_i64` for
//!   64). After a sub-32-bit op, truncate to re-establish the invariant; for
//!   signed sub-32-bit ops, sign-extend operands first.

use rustc_hash::{FxHashMap as HashMap, FxHashSet as HashSet};

use crate::ast::*;
use crate::layout::Layout;

/// Size in bytes of the stack-alloc region (software stack for `alloca` and
/// address-taken locals). Emitted as a single `.zero` directive.
const STACK_ALLOC_SIZE: u64 = 8 * 1024 * 1024;

pub struct Codegen<'a>
{
    module: &'a Module,
    layout: Layout<'a>,
    out: String,
    /// Names of functions with a body in this module. A direct call to any
    /// other `@name` (a bare `declare`, an unimplemented libc/intrinsic helper)
    /// is rejected rather than emitting a dangling label reference.
    defined_fns: HashSet<&'a str>,
    /// Counter for generating unique labels (branch edges, select, switch).
    label_counter: usize,
    /// Constant-expression values that can't be a static directive, initialized
    /// by code at program startup: (global label, byte offset, expression).
    runtime_inits: Vec<(String, u64, ConstExpr)>,
}

/// Per-function lowering context.
struct FnCtx<'f>
{
    name: String,
    /// Parameter name -> argument index.
    params: HashMap<&'f str, usize>,
    /// Instruction-result name -> local slot index.
    slots: HashMap<&'f str, usize>,
    /// Block label -> basic block (for resolving phi edges).
    blocks: HashMap<&'f str, &'f BasicBlock>,
    /// Alloca result name -> byte offset within the stack-alloc frame.
    alloca_offsets: HashMap<&'f str, u64>,
    /// Total size of this function's stack-alloc frame (0 if no allocas).
    frame_size: u64,
    /// Local slot holding the saved stack-alloc pointer (valid iff frame_size>0).
    bp_slot: usize,
}

impl<'a> Codegen<'a>
{
    pub fn new(module: &'a Module) -> Self
    {
        let defined_fns = module
            .functions
            .iter()
            .filter(|f| !f.is_decl())
            .map(|f| f.name.as_str())
            .collect();
        Codegen {
            module,
            layout: Layout::new(module),
            out: String::new(),
            defined_fns,
            label_counter: 0,
            runtime_inits: vec![],
        }
    }

    pub fn generate(mut self) -> Result<String, String>
    {
        self.line("#");
        self.line("# Generated by the llbc compiler (LLVM IR -> UVM).");
        self.line("#");
        self.line("");
        self.gen_data()?;
        self.gen_code()?;
        Ok(self.out)
    }

    fn gen_data(&mut self) -> Result<(), String>
    {
        self.line(".data;");
        self.line("");
        // Software stack pointer for the alloca region (initialized to the base
        // address of the buffer, which is emitted at the end of the section).
        self.line(".align 8;");
        self.line("__stack_alloc_sp__:");
        self.line(".addr64 __stack_alloc_buf__;");
        self.line("");

        let module = self.module;
        for g in &module.globals {
            self.emit_global(g)?;
        }

        self.line(".align 8;");
        self.line("__stack_alloc_buf__:");
        self.line(&format!(".zero {};", STACK_ALLOC_SIZE));
        self.line("");
        Ok(())
    }

    fn gen_code(&mut self) -> Result<(), String>
    {
        self.line(".code;");

        // Initialize globals whose initializer is a constant expression.
        if !self.runtime_inits.is_empty() {
            self.line("# initialize const-expression globals");
            let inits = std::mem::take(&mut self.runtime_inits);
            for (label, off, ce) in &inits {
                self.line(&format!("push {};", label));
                if *off != 0 {
                    self.push_int(*off as i128, 64);
                    self.line("add_u64;");
                }
                self.emit_const_expr(ce)?;
                self.line("store_u64;");
            }
            self.line("");
        }

        self.line("# program entry: run main, then halt with its return value");
        self.line("call main, 0;");
        self.line("ret;");
        self.line("");

        // Copy out the module reference so the loop doesn't borrow `self`.
        let module = self.module;
        for f in &module.functions {
            if !f.is_decl() {
                self.gen_function(f)?;
            }
        }
        Ok(())
    }

    fn gen_function(&mut self, f: &'a Function) -> Result<(), String>
    {
        // Build the lowering context: parameter and result-slot maps.
        let mut params = HashMap::default();
        for (i, p) in f.params.iter().enumerate() {
            if let Some(name) = &p.name {
                params.insert(name.as_str(), i);
            }
        }
        let mut slots = HashMap::default();
        let mut num_slots = 0usize;
        let mut blocks = HashMap::default();
        for bb in &f.blocks {
            blocks.insert(bb.label.as_str(), bb);
            for inst in &bb.insts {
                if let Some(dest) = &inst.dest {
                    slots.insert(dest.as_str(), num_slots);
                    num_slots += 1;
                }
            }
        }
        // Lay out the stack-alloc frame: assign each alloca a byte offset.
        let mut alloca_offsets = HashMap::default();
        let mut frame_off = 0u64;
        for bb in &f.blocks {
            for inst in &bb.insts {
                if let InstKind::Alloca { ty, count, .. } = &inst.kind {
                    let dest = inst.dest.as_deref().ok_or("alloca without result")?;
                    let n: u64 = match count {
                        None => 1,
                        Some(tv) => match &tv.val {
                            Value::Int(c) => *c as u64,
                            _ => return Err("dynamic (variable-length) alloca not supported".into()),
                        },
                    };
                    frame_off = align_up(frame_off, self.layout.align_of(ty));
                    alloca_offsets.insert(dest, frame_off);
                    frame_off += self.layout.size_of(ty) * n;
                }
            }
        }
        let frame_size = align_up(frame_off, 8);
        let bp_slot = num_slots;
        let total_slots = num_slots + if frame_size > 0 { 1 } else { 0 };

        let ctx = FnCtx {
            name: sanitize(&f.name),
            params,
            slots,
            blocks,
            alloca_offsets,
            frame_size,
            bp_slot,
        };

        self.line(&format!("# {} @{}({} params)", type_str(&f.ret_ty), f.name, f.params.len()));
        self.line(&format!("{}:", ctx.name));

        // Reserve local slots (push_0n takes a u16 operand).
        if total_slots > 0 {
            if total_slots > u16::MAX as usize {
                return Err(format!("function {} needs {} locals (> 65535)", f.name, total_slots));
            }
            self.line(&format!("push_0n {};", total_slots));
        }

        // Enter the stack-alloc frame: save the bump pointer, advance it.
        if frame_size > 0 {
            self.line("push __stack_alloc_sp__;");
            self.line("load_u64;");
            self.line("dup;");
            self.line(&format!("set_local {};", ctx.bp_slot));
            self.line(&format!("push {};", frame_size));
            self.line("add_u64;");
            self.line("push __stack_alloc_sp__;");
            self.line("swap;");
            self.line("store_u64;");
        }

        for bb in &f.blocks {
            self.line(&format!("{}:", block_label(&ctx.name, &bb.label)));
            for inst in &bb.insts {
                self.gen_inst(&ctx, inst)?;
            }
            self.gen_term(&ctx, &bb.label, &bb.term)?;
        }

        self.line("");
        Ok(())
    }

    // -- instructions ---------------------------------------------------------

    fn gen_inst(&mut self, ctx: &FnCtx, inst: &Inst) -> Result<(), String>
    {
        match &inst.kind {
            InstKind::Bin { op, ty, lhs, rhs } => {
                self.gen_bin(ctx, *op, ty, lhs, rhs)?;
                self.store_dest(ctx, inst.dest.as_deref())?;
            }
            InstKind::Conv { op, from_ty, val, to_ty } => {
                self.gen_conv(ctx, *op, from_ty, val, to_ty)?;
                self.store_dest(ctx, inst.dest.as_deref())?;
            }
            InstKind::ICmp { pred, ty, lhs, rhs } => {
                self.gen_icmp(ctx, *pred, ty, lhs, rhs)?;
                self.store_dest(ctx, inst.dest.as_deref())?;
            }
            InstKind::Select { cond, ty, tval, fval } => {
                self.gen_select(ctx, cond, ty, tval, fval)?;
                self.store_dest(ctx, inst.dest.as_deref())?;
            }
            InstKind::Load { ty, ptr, .. } => {
                let bits = self.scalar_bits(ty)?;
                self.push_value(ctx, ptr, 64)?;
                self.line(&format!("load_u{};", bits));
                self.store_dest(ctx, inst.dest.as_deref())?;
            }
            InstKind::Store { ty, val, ptr, .. } => {
                let bits = self.scalar_bits(ty)?;
                self.push_value(ctx, ptr, 64)?; // address (popped second by store)
                self.push_value(ctx, val, int_width(ty)?)?; // value (popped first)
                self.line(&format!("store_u{};", bits));
            }
            InstKind::Alloca { .. } => {
                let dest = inst.dest.as_deref().ok_or("alloca without result")?;
                let off = *ctx.alloca_offsets.get(dest).ok_or("alloca not in frame")?;
                self.line(&format!("get_local {};", ctx.bp_slot));
                if off != 0 {
                    self.push_int(off as i128, 64);
                    self.line("add_u64;");
                }
                self.store_dest(ctx, Some(dest))?;
            }
            InstKind::GetElementPtr { base_ty, ptr, indices, .. } => {
                self.gen_gep(ctx, base_ty, ptr, indices)?;
                self.store_dest(ctx, inst.dest.as_deref())?;
            }
            InstKind::Call { callee, args, ret_ty, .. } => {
                // `@llvm.*` intrinsics are lowered inline (or to a syscall), not
                // called; everything else is an ordinary UVM call.
                match callee {
                    Value::Global(name) if name.starts_with("llvm.") => {
                        self.gen_intrinsic(ctx, inst.dest.as_deref(), name, ret_ty, args)?;
                    }
                    _ => self.gen_call(ctx, inst.dest.as_deref(), callee, args)?,
                }
            }
            // Phi results are written on the predecessor edges, so the phi
            // instruction itself emits no code.
            InstKind::Phi { .. } => {}
            other => return Err(format!("codegen: instruction not yet implemented: {}", kind_name(other))),
        }
        Ok(())
    }

    fn gen_bin(&mut self, ctx: &FnCtx, op: BinOp, ty: &Type, lhs: &Value, rhs: &Value) -> Result<(), String>
    {
        let w = int_width(ty)?;
        let ow = if w <= 32 { 32 } else { 64 };
        let signed = matches!(op, BinOp::SDiv | BinOp::SRem | BinOp::AShr);

        // lhs is always a value operand.
        self.push_value(ctx, lhs, w)?;
        if signed && w < ow {
            self.emit_sext(w, ow)?;
        }
        // rhs: a value for div/rem (sign-extend if signed); a shift count for shifts.
        self.push_value(ctx, rhs, w)?;
        if matches!(op, BinOp::SDiv | BinOp::SRem) && w < ow {
            self.emit_sext(w, ow)?;
        }

        self.line(&format!("{};", bin_mnemonic(op, ow)));

        // Re-establish the width invariant for sub-32-bit results.
        if w < 32 {
            self.emit_trunc_to(w);
        }
        Ok(())
    }

    fn gen_conv(&mut self, ctx: &FnCtx, op: ConvOp, from_ty: &Type, val: &Value, to_ty: &Type) -> Result<(), String>
    {
        let fw = int_width(from_ty)?;
        let tw = int_width(to_ty)?;
        self.push_value(ctx, val, fw)?;
        self.emit_conv_op(op, fw, tw)
    }

    /// Emit the width-adjusting op for a conversion whose operand is already on
    /// the stack (shared by instruction and constant-expression conversions).
    fn emit_conv_op(&mut self, op: ConvOp, fw: u32, tw: u32) -> Result<(), String>
    {
        match op {
            // trunc to a narrower width.
            ConvOp::Trunc => self.emit_trunc_to(tw),
            // The value is already zero-extended in its slot, so zext is free.
            ConvOp::ZExt => {}
            ConvOp::SExt => self.emit_sext(fw, tw)?,
            // Pointers are 64-bit ints; only width adjustment is needed.
            ConvOp::PtrToInt => {
                if tw < 64 {
                    self.emit_trunc_to(tw);
                }
            }
            ConvOp::IntToPtr => {} // zero-extend to 64-bit = no-op
            ConvOp::BitCast => {}  // same bits
        }
        Ok(())
    }

    // -- memory addressing ----------------------------------------------------

    /// Lower a `getelementptr` to address arithmetic: base + Σ index·stride,
    /// with constant contributions folded into a single added constant.
    fn gen_gep(&mut self, ctx: &FnCtx, base_ty: &Type, ptr: &Value, indices: &[TypedVal]) -> Result<(), String>
    {
        // Walk the indices, separating constant offset from variable terms.
        let mut const_off: i128 = 0;
        // (index value, index width, stride)
        let mut var_terms: Vec<(&Value, u32, u64)> = vec![];
        let mut cur_ty: Type = base_ty.clone();

        for (k, idx) in indices.iter().enumerate() {
            if k == 0 {
                // First index strides over the base type (pointer-as-array).
                let stride = self.layout.size_of(base_ty);
                match &idx.val {
                    Value::Int(c) => const_off += *c * stride as i128,
                    _ => var_terms.push((&idx.val, int_width(&idx.ty)?, stride)),
                }
            } else {
                match gep_step(&self.layout, &cur_ty, idx)? {
                    Step::Const(off, next) => {
                        const_off += off;
                        cur_ty = next;
                    }
                    Step::Var(stride, next) => {
                        var_terms.push((&idx.val, int_width(&idx.ty)?, stride));
                        cur_ty = next;
                    }
                }
            }
        }

        // Emit: base, then each variable term, then the constant.
        self.push_value(ctx, ptr, 64)?;
        for (val, w, stride) in &var_terms {
            self.push_value(ctx, val, *w)?;
            if *w < 64 {
                self.emit_sext(*w, 64)?; // GEP indices are signed
            }
            self.push_int(*stride as i128, 64);
            self.line("mul_u64;");
            self.line("add_u64;");
        }
        if const_off != 0 {
            self.push_int(const_off, 64);
            self.line("add_u64;");
        }
        Ok(())
    }

    fn emit_frame_leave(&mut self, ctx: &FnCtx)
    {
        if ctx.frame_size > 0 {
            self.line("push __stack_alloc_sp__;");
            self.line(&format!("get_local {};", ctx.bp_slot));
            self.line("store_u64;");
        }
    }

    /// Bit width of a scalar load/store (8/16/32/64).
    fn scalar_bits(&self, ty: &Type) -> Result<u32, String>
    {
        let bytes = self.layout.size_of(ty);
        match bytes {
            1 => Ok(8),
            2 => Ok(16),
            4 => Ok(32),
            8 => Ok(64),
            _ => Err(format!("load/store of non-scalar type {} ({} bytes)", type_str(ty), bytes)),
        }
    }

    // -- globals (.data) ------------------------------------------------------

    fn emit_global(&mut self, g: &'a Global) -> Result<(), String>
    {
        let label = sanitize(&g.name);
        let align = self.layout.align_of(&g.ty);
        let size = self.layout.size_of(&g.ty);
        self.line(&format!(".align {};", align));
        self.line(&format!("{}:", label));
        match &g.init {
            None => self.line(&format!(".zero {};", size)),
            Some(v) => self.emit_const_data(&label, 0, &g.ty, v)?,
        }
        self.line("");
        Ok(())
    }

    /// Emit the raw bytes of a constant initializer of `ty`, where the data
    /// lives at `offset` bytes into the global labelled `base`. Constant
    /// expressions (which can't be a static directive) reserve space and are
    /// stored at `base + offset` by startup code.
    fn emit_const_data(&mut self, base: &str, offset: u64, ty: &Type, val: &Value) -> Result<(), String>
    {
        match val {
            Value::Int(c) => {
                let bits = self.scalar_bits(ty)?;
                self.line(&format!(".u{} {};", bits, mask_to_width(*c, bits)));
            }
            Value::Null => self.line(".u64 0;"),
            Value::ZeroInit | Value::Undef | Value::Poison => {
                self.line(&format!(".zero {};", self.layout.size_of(ty)));
            }
            Value::CStr(bytes) => self.emit_hex_bytes(bytes),
            Value::Global(name) => self.line(&format!(".addr64 {};", sanitize(name))),
            Value::Array(elems) => {
                let mut o = offset;
                for e in elems {
                    self.emit_const_data(base, o, &e.ty, &e.val)?;
                    o += self.layout.size_of(&e.ty);
                }
            }
            Value::Struct(fields) => self.emit_struct_data(base, offset, ty, fields)?,
            Value::ConstExpr(ce) => {
                self.line(&format!(".zero {};", self.layout.size_of(ty)));
                self.runtime_inits.push((base.to_string(), offset, (**ce).clone()));
            }
            Value::Local(_) => return Err("local value in a constant initializer".into()),
        }
        Ok(())
    }

    /// Emit a struct constant, inserting padding so fields land at the offsets
    /// the layout computes.
    fn emit_struct_data(&mut self, base: &str, offset: u64, ty: &Type, fields: &[TypedVal]) -> Result<(), String>
    {
        let offsets: Vec<u64> = {
            let body = match ty {
                Type::Struct(b) => b,
                Type::NamedStruct(n) => self.layout.resolve(n),
                _ => return Err(format!("struct initializer for non-struct type {}", type_str(ty))),
            };
            (0..fields.len()).map(|i| self.layout.field_offset(body, i)).collect()
        };
        let total = self.layout.size_of(ty);
        let mut off = 0u64;
        for (i, f) in fields.iter().enumerate() {
            if offsets[i] > off {
                self.line(&format!(".zero {};", offsets[i] - off));
            }
            self.emit_const_data(base, offset + offsets[i], &f.ty, &f.val)?;
            off = offsets[i] + self.layout.size_of(&f.ty);
        }
        if total > off {
            self.line(&format!(".zero {};", total - off));
        }
        Ok(())
    }

    fn emit_hex_bytes(&mut self, bytes: &[u8])
    {
        if bytes.is_empty() {
            return;
        }
        let mut s = String::from(".hex ");
        for b in bytes {
            s.push_str(&format!("{:02x}", b));
        }
        s.push(';');
        self.line(&s);
    }

    // -- constant expressions (push the runtime value) ------------------------

    fn emit_const_expr(&mut self, ce: &ConstExpr) -> Result<(), String>
    {
        match ce {
            ConstExpr::GetElementPtr { base_ty, base, indices, .. } => {
                self.emit_const_value(&base.ty, &base.val)?;
                let off = const_gep_offset(&self.layout, base_ty, indices)?;
                if off != 0 {
                    self.push_int(off, 64);
                    self.line("add_u64;");
                }
            }
            ConstExpr::Conv { op, val, to } => {
                self.emit_const_value(&val.ty, &val.val)?;
                self.emit_conv_op(*op, int_width(&val.ty)?, int_width(to)?)?;
            }
            ConstExpr::Bin { op, lhs, rhs } => {
                self.emit_const_value(&lhs.ty, &lhs.val)?;
                self.emit_const_value(&rhs.ty, &rhs.val)?;
                let w = int_width(&lhs.ty)?;
                let ow = if w <= 32 { 32 } else { 64 };
                self.line(&format!("{};", bin_mnemonic(*op, ow)));
            }
        }
        Ok(())
    }

    fn emit_const_value(&mut self, ty: &Type, val: &Value) -> Result<(), String>
    {
        match val {
            Value::Int(c) => self.push_int(*c, int_width(ty).unwrap_or(64)),
            Value::Null | Value::ZeroInit => self.line("push 0;"),
            Value::Global(name) => self.line(&format!("push {};", sanitize(name))),
            Value::ConstExpr(ce) => self.emit_const_expr(ce)?,
            _ => return Err(format!("unsupported constant value: {:?}", val)),
        }
        Ok(())
    }

    fn gen_icmp(&mut self, ctx: &FnCtx, pred: ICmpPred, ty: &Type, lhs: &Value, rhs: &Value) -> Result<(), String>
    {
        let w = int_width(ty)?;
        let ow = if w <= 32 { 32 } else { 64 };
        let signed = matches!(pred, ICmpPred::Sgt | ICmpPred::Sge | ICmpPred::Slt | ICmpPred::Sle);

        self.push_value(ctx, lhs, w)?;
        if signed && w < ow {
            self.emit_sext(w, ow)?;
        }
        self.push_value(ctx, rhs, w)?;
        if signed && w < ow {
            self.emit_sext(w, ow)?;
        }
        self.line(&format!("{};", icmp_mnemonic(pred, ow)));
        // Result is an i1 (0/1), already satisfying the width invariant.
        Ok(())
    }

    fn gen_select(&mut self, ctx: &FnCtx, cond: &Value, ty: &Type, tval: &Value, fval: &Value) -> Result<(), String>
    {
        let w = int_width(ty)?;
        let l_false = self.fresh_label("sel_false");
        let l_done = self.fresh_label("sel_done");

        self.push_value(ctx, cond, 1)?;
        self.line(&format!("jz {};", l_false));
        self.push_value(ctx, tval, w)?;
        self.line(&format!("jmp {};", l_done));
        self.line(&format!("{}:", l_false));
        self.push_value(ctx, fval, w)?;
        self.line(&format!("{}:", l_done));
        // The selected value is left on the stack for store_dest.
        Ok(())
    }

    // -- calls ----------------------------------------------------------------

    /// Lower a `call`. Arguments are pushed left-to-right (arg 0 first, so it
    /// lands at the callee's `get_arg 0`); varargs need no special handling —
    /// the caller just pushes every actual argument, fixed and variadic. A
    /// direct call names its label; an indirect call pushes the function
    /// pointer last (on top of the args) and uses `call_fp`. Every UVM call
    /// yields exactly one return value, bound to the result slot or discarded.
    fn gen_call(&mut self, ctx: &FnCtx, dest: Option<&str>, callee: &Value, args: &[TypedVal]) -> Result<(), String>
    {
        if args.len() > u8::MAX as usize {
            return Err(format!("call with {} args (> 255 not supported)", args.len()));
        }
        for a in args {
            let w = int_width(&a.ty)?;
            self.push_value(ctx, &a.val, w)?;
        }

        match callee {
            Value::Global(name) => {
                if !self.defined_fns.contains(name.as_str()) {
                    return Err(format!("call to undefined function @{} (external/intrinsic not yet supported)", name));
                }
                self.line(&format!("call {}, {};", sanitize(name), args.len()));
            }
            Value::Local(_) => {
                // Function pointer goes on top of the stack for call_fp.
                self.push_value(ctx, callee, 64)?;
                self.line(&format!("call_fp {};", args.len()));
            }
            other => return Err(format!("unsupported call target: {:?}", other)),
        }

        match dest {
            Some(name) => {
                let slot = *ctx.slots.get(name).ok_or_else(|| format!("no slot for %{}", name))?;
                self.line(&format!("set_local {};", slot));
            }
            None => self.line("pop;"),
        }
        Ok(())
    }

    // -- intrinsics -----------------------------------------------------------

    /// Lower an `@llvm.*` intrinsic. `memcpy`/`memset` map onto the native UVM
    /// syscalls; `lifetime.*` is dropped; the small arithmetic intrinsics
    /// expand inline to a handful of stack ops (no call, no runtime helper).
    /// The trailing metadata args LLVM passes (the `i1 volatile` on the memory
    /// intrinsics, the `i1 is_int_min_poison` on `abs`) are ignored.
    fn gen_intrinsic(&mut self, ctx: &FnCtx, dest: Option<&str>, name: &str, ret_ty: &Type, args: &[TypedVal]) -> Result<(), String>
    {
        let bare = &name["llvm.".len()..];

        // --- void intrinsics (no result) ---
        if bare.starts_with("lifetime.") {
            return Ok(()); // a scoping hint; emit nothing
        }
        if bare.starts_with("memcpy.") {
            // (dst, src, len, i1 volatile) -> UVM `memcpy(dst, src, num_bytes)`.
            self.push_value(ctx, &args[0].val, 64)?; // dst
            self.push_value(ctx, &args[1].val, 64)?; // src
            self.push_value(ctx, &args[2].val, 64)?; // num_bytes
            self.line("syscall memcpy;");
            return Ok(());
        }
        if bare.starts_with("memset.") {
            // (dst, i8 value, len, i1 volatile) -> UVM `memset(dst, value, num_bytes)`.
            self.push_value(ctx, &args[0].val, 64)?; // dst
            self.push_value(ctx, &args[1].val, 8)?;  // fill byte
            self.push_value(ctx, &args[2].val, 64)?; // num_bytes
            self.line("syscall memset;");
            return Ok(());
        }

        // --- value-producing intrinsics ---
        let a = &args[0].val;
        if bare.starts_with("abs.") {
            self.gen_abs(ctx, a, ret_ty)?;
        } else if bare.starts_with("smax.") {
            self.gen_minmax(ctx, a, &args[1].val, ret_ty, true, true)?;
        } else if bare.starts_with("smin.") {
            self.gen_minmax(ctx, a, &args[1].val, ret_ty, false, true)?;
        } else if bare.starts_with("umax.") {
            self.gen_minmax(ctx, a, &args[1].val, ret_ty, true, false)?;
        } else if bare.starts_with("umin.") {
            self.gen_minmax(ctx, a, &args[1].val, ret_ty, false, false)?;
        } else if bare.starts_with("scmp.") {
            self.gen_three_way(ctx, a, &args[1].val, &args[0].ty, ret_ty, true)?;
        } else if bare.starts_with("ucmp.") {
            self.gen_three_way(ctx, a, &args[1].val, &args[0].ty, ret_ty, false)?;
        } else if bare.starts_with("usub.sat.") {
            self.gen_usub_sat(ctx, a, &args[1].val, ret_ty)?;
        } else if bare.starts_with("bitreverse.") {
            let w = int_width(ret_ty)?;
            if w != 8 {
                return Err(format!("llvm.bitreverse only supported for i8 (got i{})", w));
            }
            self.gen_bitreverse8(ctx, a)?;
        } else {
            return Err(format!("unsupported intrinsic @{}", name));
        }

        self.store_dest(ctx, dest)
    }

    /// `abs(x)` = `x < 0 ? -x : x`. INT_MIN wraps to itself, which matches the
    /// intrinsic's poison-on-INT_MIN contract (any result is acceptable there).
    fn gen_abs(&mut self, ctx: &FnCtx, x: &Value, ty: &Type) -> Result<(), String>
    {
        let w = int_width(ty)?;
        let ow = if w <= 32 { 32 } else { 64 };
        let l_neg = self.fresh_label("abs_neg");
        let l_done = self.fresh_label("abs_done");

        // cond = x < 0 (signed)
        self.push_value(ctx, x, w)?;
        if w < ow { self.emit_sext(w, ow)?; }
        self.push_int(0, ow);
        self.line(&format!("lt_i{};", ow));
        self.line(&format!("jnz {};", l_neg));

        // x >= 0: the value is x itself.
        self.push_value(ctx, x, w)?;
        self.line(&format!("jmp {};", l_done));

        // x < 0: 0 - x.
        self.line(&format!("{}:", l_neg));
        self.push_int(0, ow);
        self.push_value(ctx, x, w)?;
        self.line(&format!("sub_u{};", ow));
        if w < 32 { self.emit_trunc_to(w); }
        self.line(&format!("{}:", l_done));
        Ok(())
    }

    /// `min`/`max` of two operands via a compare + branch (the UVM `select` op
    /// indexes slots, not stack values, so it can't be used here).
    fn gen_minmax(&mut self, ctx: &FnCtx, a: &Value, b: &Value, ty: &Type, is_max: bool, signed: bool) -> Result<(), String>
    {
        let w = int_width(ty)?;
        let lt = if signed { ICmpPred::Slt } else { ICmpPred::Ult };
        self.gen_icmp(ctx, lt, ty, a, b)?; // cond = a < b
        let l_else = self.fresh_label("mm_else");
        let l_done = self.fresh_label("mm_done");
        self.line(&format!("jz {};", l_else));
        // a < b: max picks b, min picks a.
        self.push_value(ctx, if is_max { b } else { a }, w)?;
        self.line(&format!("jmp {};", l_done));
        self.line(&format!("{}:", l_else));
        // a >= b: max picks a, min picks b.
        self.push_value(ctx, if is_max { a } else { b }, w)?;
        self.line(&format!("{}:", l_done));
        Ok(())
    }

    /// Three-way compare (`scmp`/`ucmp`): `(a > b) - (a < b)` in {-1, 0, 1}.
    /// The compare uses the operand type `op_ty`; the result width is `ret_ty`.
    fn gen_three_way(&mut self, ctx: &FnCtx, a: &Value, b: &Value, op_ty: &Type, ret_ty: &Type, signed: bool) -> Result<(), String>
    {
        let (gt, lt) = if signed {
            (ICmpPred::Sgt, ICmpPred::Slt)
        } else {
            (ICmpPred::Ugt, ICmpPred::Ult)
        };
        self.gen_icmp(ctx, gt, op_ty, a, b)?; // g (0/1)
        self.gen_icmp(ctx, lt, op_ty, a, b)?; // l (0/1)  -> stack [g, l]
        let rw = int_width(ret_ty)?;
        let sw = if rw <= 32 { 32 } else { 64 };
        self.line(&format!("sub_u{};", sw)); // g - l  (wraps to -1 at the result width)
        if rw < 32 { self.emit_trunc_to(rw); }
        Ok(())
    }

    /// Unsigned saturating subtract: `a > b ? a - b : 0`.
    fn gen_usub_sat(&mut self, ctx: &FnCtx, a: &Value, b: &Value, ty: &Type) -> Result<(), String>
    {
        let w = int_width(ty)?;
        let ow = if w <= 32 { 32 } else { 64 };
        self.gen_icmp(ctx, ICmpPred::Ugt, ty, a, b)?; // cond = a > b
        let l_zero = self.fresh_label("usat_zero");
        let l_done = self.fresh_label("usat_done");
        self.line(&format!("jz {};", l_zero));
        self.push_value(ctx, a, w)?;
        self.push_value(ctx, b, w)?;
        self.line(&format!("sub_u{};", ow));
        if w < 32 { self.emit_trunc_to(w); }
        self.line(&format!("jmp {};", l_done));
        self.line(&format!("{}:", l_zero));
        self.line("push 0;");
        self.line(&format!("{}:", l_done));
        Ok(())
    }

    /// Reverse the bits of a byte with the classic branchless 64-bit trick:
    /// `((b * 0x0202020202) & 0x010884422010) % 1023`.
    fn gen_bitreverse8(&mut self, ctx: &FnCtx, x: &Value) -> Result<(), String>
    {
        self.push_value(ctx, x, 8)?;
        self.push_int(0x0202020202, 64);
        self.line("mul_u64;");
        self.push_int(0x010884422010, 64);
        self.line("and_u64;");
        self.push_int(1023, 64);
        self.line("mod_u64;"); // result is 0..255, already a valid i8 slot
        Ok(())
    }

    // -- terminators ----------------------------------------------------------

    fn gen_term(&mut self, ctx: &FnCtx, pred: &str, term: &Terminator) -> Result<(), String>
    {
        match term {
            Terminator::Ret { val } => match val {
                None => {
                    // `ret void`: UVM `ret` always returns a value, push 0.
                    self.line("push 0;");
                    self.emit_frame_leave(ctx);
                    self.line("ret;");
                }
                Some(tv) => {
                    let w = int_width(&tv.ty)?;
                    self.push_value(ctx, &tv.val, w)?;
                    self.emit_frame_leave(ctx);
                    self.line("ret;");
                }
            },

            Terminator::Br { cond: None, if_true, .. } => {
                self.emit_edge_copies(ctx, pred, if_true)?;
                self.line(&format!("jmp {};", block_label(&ctx.name, if_true)));
            }

            Terminator::Br { cond: Some(c), if_true, if_false } => {
                let if_false = if_false.as_deref().ok_or("conditional br missing false target")?;
                // Each branch edge gets its own phi-copy sequence, which makes
                // critical edges correct without an explicit splitting pass.
                self.push_value(ctx, c, 1)?;
                let l_false = self.fresh_label("br_false");
                self.line(&format!("jz {};", l_false));
                self.emit_edge_copies(ctx, pred, if_true)?;
                self.line(&format!("jmp {};", block_label(&ctx.name, if_true)));
                self.line(&format!("{}:", l_false));
                self.emit_edge_copies(ctx, pred, if_false)?;
                self.line(&format!("jmp {};", block_label(&ctx.name, if_false)));
            }

            Terminator::Switch { ty, val, default, cases } => {
                let w = int_width(ty)?;
                let ow = if w <= 32 { 32 } else { 64 };
                let mut case_targets = Vec::with_capacity(cases.len());
                for (cv, target) in cases {
                    let l_case = self.fresh_label("sw_case");
                    self.push_value(ctx, val, w)?;
                    self.push_int(*cv, w);
                    self.line(&format!("eq_u{};", ow));
                    self.line(&format!("jnz {};", l_case));
                    case_targets.push((l_case, target));
                }
                // Fall through to the default edge.
                self.emit_edge_copies(ctx, pred, default)?;
                self.line(&format!("jmp {};", block_label(&ctx.name, default)));
                // Then the per-case edges.
                for (l_case, target) in case_targets {
                    self.line(&format!("{}:", l_case));
                    self.emit_edge_copies(ctx, pred, target)?;
                    self.line(&format!("jmp {};", block_label(&ctx.name, target)));
                }
            }

            Terminator::Unreachable => self.line("panic;"),
        }
        Ok(())
    }

    /// Emit the phi assignments for the edge `pred -> succ_label`, as a parallel
    /// copy (push all incoming values, then store them into the phi slots in
    /// reverse, so all reads happen before any writes).
    fn emit_edge_copies(&mut self, ctx: &FnCtx, pred: &str, succ_label: &str) -> Result<(), String>
    {
        let succ = match ctx.blocks.get(succ_label) {
            Some(b) => *b,
            None => return Err(format!("branch to unknown block %{}", succ_label)),
        };

        let mut copies: Vec<(usize, &Value, &Type)> = vec![];
        for inst in &succ.insts {
            match &inst.kind {
                InstKind::Phi { ty, incoming } => {
                    let dest = inst.dest.as_deref().ok_or("phi without result name")?;
                    let slot = *ctx
                        .slots
                        .get(dest)
                        .ok_or_else(|| format!("no slot for phi %{}", dest))?;
                    let val = incoming
                        .iter()
                        .find(|(_, p)| p == pred)
                        .map(|(v, _)| v)
                        .ok_or_else(|| format!("phi %{} has no incoming value for predecessor %{}", dest, pred))?;
                    copies.push((slot, val, ty));
                }
                // Phis are only at the start of a block.
                _ => break,
            }
        }

        for (_, val, ty) in &copies {
            let w = int_width(ty)?;
            self.push_value(ctx, val, w)?;
        }
        for (slot, _, _) in copies.iter().rev() {
            self.line(&format!("set_local {};", slot));
        }
        Ok(())
    }

    fn fresh_label(&mut self, hint: &str) -> String
    {
        let n = self.label_counter;
        self.label_counter += 1;
        format!("__{}_{}", hint, n)
    }

    // -- operands -------------------------------------------------------------

    /// Push a value operand (of the given bit width) onto the stack.
    fn push_value(&mut self, ctx: &FnCtx, val: &Value, width: u32) -> Result<(), String>
    {
        match val {
            Value::Local(name) => {
                if let Some(&idx) = ctx.params.get(name.as_str()) {
                    self.line(&format!("get_arg {};", idx));
                } else if let Some(&slot) = ctx.slots.get(name.as_str()) {
                    self.line(&format!("get_local {};", slot));
                } else {
                    return Err(format!("undefined value %{} in {}", name, ctx.name));
                }
            }
            Value::Int(v) => self.push_int(*v, width),
            Value::Null => self.line("push 0;"),
            Value::Undef | Value::Poison | Value::ZeroInit => self.line("push 0;"),
            // The address of a global or function (both are plain labels).
            Value::Global(name) => self.line(&format!("push {};", sanitize(name))),
            Value::ConstExpr(ce) => self.emit_const_expr(ce)?,
            other => return Err(format!("codegen: operand not yet implemented: {:?}", other)),
        }
        Ok(())
    }

    /// Push an integer constant as its zero-extended `width`-bit pattern, so the
    /// slot satisfies the representation invariant.
    fn push_int(&mut self, v: i128, width: u32)
    {
        self.line(&format!("push {};", mask_to_width(v, width)));
    }

    fn store_dest(&mut self, ctx: &FnCtx, dest: Option<&str>) -> Result<(), String>
    {
        match dest {
            Some(name) => {
                let slot = *ctx.slots.get(name).ok_or_else(|| format!("no slot for %{}", name))?;
                self.line(&format!("set_local {};", slot));
                Ok(())
            }
            None => Err("value-producing instruction has no result name".to_string()),
        }
    }

    // -- width adjustment -----------------------------------------------------

    /// Sign-extend the top-of-stack value from `from` bits to `to` bits.
    fn emit_sext(&mut self, from: u32, to: u32) -> Result<(), String>
    {
        // Direct ops: sx_i{8,16,32}_i{32,64}. For an intermediate width we
        // sign-extend to 32 or 64 and then truncate.
        let mid = if to <= 32 { 32 } else { 64 };
        if (from == 8 || from == 16 || from == 32) && from < mid {
            self.line(&format!("sx_i{}_i{};", from, mid));
            if to < mid {
                self.emit_trunc_to(to);
            }
            Ok(())
        } else {
            Err(format!("unsupported sign extension i{} -> i{}", from, to))
        }
    }

    /// Truncate the top-of-stack value to `w` bits (clearing the upper bits).
    fn emit_trunc_to(&mut self, w: u32)
    {
        match w {
            1 => {
                self.line("push 1;");
                self.line("and_u32;");
            }
            8 => self.line("trunc_u8;"),
            16 => self.line("trunc_u16;"),
            32 => self.line("trunc_u32;"),
            _ => {} // 64: nothing to do
        }
    }

    // -- output ---------------------------------------------------------------

    fn line(&mut self, s: &str)
    {
        self.out.push_str(s);
        self.out.push('\n');
    }
}

// ===========================================================================
// Helpers
// ===========================================================================

/// Integer/pointer bit width (pointers are 64-bit).
fn int_width(ty: &Type) -> Result<u32, String>
{
    match ty {
        Type::Int(w) => Ok(*w),
        Type::Ptr => Ok(64),
        _ => Err(format!("expected an integer/pointer type, got {}", type_str(ty))),
    }
}

fn bin_mnemonic(op: BinOp, w: u32) -> &'static str
{
    use BinOp::*;
    match (op, w) {
        (Add, 32) => "add_u32", (Add, 64) => "add_u64",
        (Sub, 32) => "sub_u32", (Sub, 64) => "sub_u64",
        (Mul, 32) => "mul_u32", (Mul, 64) => "mul_u64",
        (And, 32) => "and_u32", (And, 64) => "and_u64",
        (Or, 32) => "or_u32", (Or, 64) => "or_u64",
        (Xor, 32) => "xor_u32", (Xor, 64) => "xor_u64",
        (Shl, 32) => "lshift_u32", (Shl, 64) => "lshift_u64",
        (LShr, 32) => "rshift_u32", (LShr, 64) => "rshift_u64",
        (AShr, 32) => "rshift_i32", (AShr, 64) => "rshift_i64",
        (UDiv, 32) => "div_u32", (UDiv, 64) => "div_u64",
        (SDiv, 32) => "div_i32", (SDiv, 64) => "div_i64",
        (URem, 32) => "mod_u32", (URem, 64) => "mod_u64",
        (SRem, 32) => "mod_i32", (SRem, 64) => "mod_i64",
        _ => unreachable!("op width must be 32 or 64"),
    }
}

fn icmp_mnemonic(pred: ICmpPred, w: u32) -> String
{
    use ICmpPred::*;
    // eq/ne are sign-agnostic (only `_u` forms exist); the ordering compares
    // pick `_i` (signed) or `_u` (unsigned).
    match pred {
        Eq => format!("eq_u{}", w),
        Ne => format!("ne_u{}", w),
        Ugt => format!("gt_u{}", w),
        Uge => format!("ge_u{}", w),
        Ult => format!("lt_u{}", w),
        Ule => format!("le_u{}", w),
        Sgt => format!("gt_i{}", w),
        Sge => format!("ge_i{}", w),
        Slt => format!("lt_i{}", w),
        Sle => format!("le_i{}", w),
    }
}

/// The result of descending one GEP index into an aggregate type.
enum Step
{
    /// A constant byte offset and the resulting element/field type.
    Const(i128, Type),
    /// A per-element stride (the index is a runtime value) and element type.
    Var(u64, Type),
}

/// Descend one GEP index into `cur_ty` (a struct or array).
fn gep_step(layout: &Layout, cur_ty: &Type, idx: &TypedVal) -> Result<Step, String>
{
    match cur_ty {
        Type::Struct(body) => struct_step(layout, body, idx),
        Type::NamedStruct(name) => struct_step(layout, layout.resolve(name), idx),
        Type::Array { elem, .. } => {
            let elem = (**elem).clone();
            let stride = layout.size_of(&elem);
            match &idx.val {
                Value::Int(c) => Ok(Step::Const(*c * stride as i128, elem)),
                _ => Ok(Step::Var(stride, elem)),
            }
        }
        _ => Err(format!("cannot index into non-aggregate type {}", type_str(cur_ty))),
    }
}

fn struct_step(layout: &Layout, body: &StructBody, idx: &TypedVal) -> Result<Step, String>
{
    let field = const_usize(&idx.val)?;
    if field >= body.fields.len() {
        return Err("struct getelementptr field index out of range".into());
    }
    Ok(Step::Const(layout.field_offset(body, field) as i128, body.fields[field].clone()))
}

/// Compute the constant byte offset of an all-constant GEP (for const-exprs).
fn const_gep_offset(layout: &Layout, base_ty: &Type, indices: &[TypedVal]) -> Result<i128, String>
{
    let mut off: i128 = 0;
    let mut cur_ty = base_ty.clone();
    for (k, idx) in indices.iter().enumerate() {
        if k == 0 {
            off += const_i128(&idx.val)? * layout.size_of(base_ty) as i128;
        } else {
            match gep_step(layout, &cur_ty, idx)? {
                Step::Const(o, next) => {
                    off += o;
                    cur_ty = next;
                }
                Step::Var(..) => return Err("non-constant index in constant getelementptr".into()),
            }
        }
    }
    Ok(off)
}

fn const_usize(v: &Value) -> Result<usize, String>
{
    match v {
        Value::Int(c) => Ok(*c as usize),
        _ => Err("expected a constant integer index".into()),
    }
}

fn const_i128(v: &Value) -> Result<i128, String>
{
    match v {
        Value::Int(c) => Ok(*c),
        _ => Err("expected a constant integer".into()),
    }
}

/// Reduce an integer constant to its zero-extended `width`-bit pattern.
fn mask_to_width(v: i128, width: u32) -> u64
{
    if width >= 64 {
        v as u128 as u64
    } else {
        ((v as u128) & ((1u128 << width) - 1)) as u64
    }
}

fn align_up(off: u64, align: u64) -> u64
{
    if align <= 1 {
        off
    } else {
        (off + align - 1) & !(align - 1)
    }
}

/// Sanitize an LLVM name into a valid UVM label (alphanumerics and `_`).
fn sanitize(name: &str) -> String
{
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

fn block_label(fn_name: &str, block: &str) -> String
{
    format!("{}__{}", fn_name, sanitize(block))
}

fn type_str(ty: &Type) -> String
{
    match ty {
        Type::Void => "void".to_string(),
        Type::Int(w) => format!("i{}", w),
        Type::Ptr => "ptr".to_string(),
        Type::Array { len, elem } => format!("[{} x {}]", len, type_str(elem)),
        Type::Struct(_) => "struct".to_string(),
        Type::NamedStruct(n) => format!("%{}", n),
        Type::Func(_) => "fn".to_string(),
        Type::Label => "label".to_string(),
        Type::Metadata => "metadata".to_string(),
    }
}

fn kind_name(k: &InstKind) -> &'static str
{
    match k {
        InstKind::Bin { .. } => "bin",
        InstKind::Conv { .. } => "conv",
        InstKind::ICmp { .. } => "icmp",
        InstKind::Select { .. } => "select",
        InstKind::Load { .. } => "load",
        InstKind::Store { .. } => "store",
        InstKind::Alloca { .. } => "alloca",
        InstKind::GetElementPtr { .. } => "getelementptr",
        InstKind::Phi { .. } => "phi",
        InstKind::Call { .. } => "call",
        InstKind::Freeze { .. } => "freeze",
    }
}

fn term_name(t: &Terminator) -> &'static str
{
    match t {
        Terminator::Ret { .. } => "ret",
        Terminator::Br { .. } => "br",
        Terminator::Switch { .. } => "switch",
        Terminator::Unreachable => "unreachable",
    }
}
